spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diary
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      log-condition-evaluation-delta: false
  #profiles:
    #active: develop
spring-doc:
  swagger-ui:
    tags-sorter: alpha
    path: /swagger-ui.html

api.dev.jwt.key: jwt-key